export const languages: { [key: string]: string } = {
  Hindi: "hi",
  French: "fr",
  Urdu: "ur",
  Filipino: "fil",
  Persian: "fa",
  Punjabi: "pa",
  Bengali: "bn",
  Russian: "ru",
  Chinese: "zh",
  Nepali: "ne",
  Marathi: "mr",
  Malay: "ms",
  // -------------------- New imported languages
  Albanian: "sq",
  Armenian: "hy",
  Azerbaijani: "az",
  Basque: "eu",
  Bosnian: "bs",
  "Brazilian Portuguese": "pt-BR",
  Bulgarian: "bg",
  Catalan: "ca",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dutch: "nl",
  Estonian: "et",
  Finnish: "fi",
  Galician: "gl",
  Georgian: "ka",
  German: "de",
  Greek: "el",
  Gujarati: "gu",
  Hungarian: "hu",
  Indonesian: "id",
  Italian: "it",
  Japanese: "ja",
  Kannada: "kn",
  Kazakh: "kk",
  Korean: "ko",
  Latvian: "lv",
  Lithuanian: "lt",
  Macedonian: "mk",
  Maltese: "mt",
  Mandarin: "zh-CN",
  Mongolian: "mn",
  Norwegian: "nb",
  Oriya: "or",
  Pashto: "ps",
  Polish: "pl",
  Portuguese: "pt",
  Romanian: "ro",
  Serbian: "sr",
  Sinhala: "si",
  Slovak: "sk",
  Slovene: "sl",
  Ukrainian: "uk",
  Uzbek: "uz",
  Vietnamese: "vi",
  Welsh: "cy",
  "zh-Hans": "zh-Hans",
  "zh-Hant": "zh-Hant",
};

export const extensions = {
  ios: ".strings",
  android: ".xml",
  portal: ".json",
};

export const platforms = {
  ios: "ios",
  android: "android",
  portal: "portal",
};
